version: '3.1'
services:
  api-catalog:
    image: adschosen/api-catalog:1.1.0
    container_name: api-catalog
    ports:
      - 6070:6070
    restart: always
    links:
      - api-catalog-db

  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306

  api-reservation-db:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: muppet
      MONGO_INITDB_DATABASE: flights_reservation
    ports:
      - 27017:27017
